# Generated by Django 4.2.7 on 2024-11-17 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prcr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
    ]
