# Generated by Django 4.2.7 on 2024-11-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prcr", "0002_alter_category_options_alter_subcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="The MimeTypeof the file",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_brand",
                to="prcr.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_subcategory",
                to="prcr.subcategory",
            ),
        ),
    ]
