# Generated by Django 4.2.7 on 2024-11-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prcr", "0003_product_content_type_product_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_brand",
                to="prcr.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_subcategory",
                to="prcr.subcategory",
            ),
        ),
    ]
