# Generated by Django 4.2.7 on 2024-11-25 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prcr", "0004_alter_product_brand_alter_product_sub_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="name",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="brand",
            old_name="company_name",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="sub_category",
            new_name="subcategory",
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="name",
            new_name="subcategory",
        ),
    ]
